# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/qyt/ttree

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/qyt/ttree

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/qyt/ttree/CMakeFiles /home/qyt/ttree/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/qyt/ttree/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named docs

# Build rule for target.
docs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 docs
.PHONY : docs

# fast build rule for target.
docs/fast:
	$(MAKE) -f CMakeFiles/docs.dir/build.make CMakeFiles/docs.dir/build
.PHONY : docs/fast

#=============================================================================
# Target rules for targets named ttree

# Build rule for target.
ttree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ttree
.PHONY : ttree

# fast build rule for target.
ttree/fast:
	$(MAKE) -f CMakeFiles/ttree.dir/build.make CMakeFiles/ttree.dir/build
.PHONY : ttree/fast

#=============================================================================
# Target rules for targets named t_balance

# Build rule for target.
t_balance: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 t_balance
.PHONY : t_balance

# fast build rule for target.
t_balance/fast:
	$(MAKE) -f tests/unit/CMakeFiles/t_balance.dir/build.make tests/unit/CMakeFiles/t_balance.dir/build
.PHONY : t_balance/fast

#=============================================================================
# Target rules for targets named t_cursor_move

# Build rule for target.
t_cursor_move: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 t_cursor_move
.PHONY : t_cursor_move

# fast build rule for target.
t_cursor_move/fast:
	$(MAKE) -f tests/unit/CMakeFiles/t_cursor_move.dir/build.make tests/unit/CMakeFiles/t_cursor_move.dir/build
.PHONY : t_cursor_move/fast

#=============================================================================
# Target rules for targets named t_init

# Build rule for target.
t_init: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 t_init
.PHONY : t_init

# fast build rule for target.
t_init/fast:
	$(MAKE) -f tests/unit/CMakeFiles/t_init.dir/build.make tests/unit/CMakeFiles/t_init.dir/build
.PHONY : t_init/fast

#=============================================================================
# Target rules for targets named t_lookup

# Build rule for target.
t_lookup: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 t_lookup
.PHONY : t_lookup

# fast build rule for target.
t_lookup/fast:
	$(MAKE) -f tests/unit/CMakeFiles/t_lookup.dir/build.make tests/unit/CMakeFiles/t_lookup.dir/build
.PHONY : t_lookup/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f tests/unit/CMakeFiles/tests.dir/build.make tests/unit/CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named utest

# Build rule for target.
utest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utest
.PHONY : utest

# fast build rule for target.
utest/fast:
	$(MAKE) -f tests/unit/CMakeFiles/utest.dir/build.make tests/unit/CMakeFiles/utest.dir/build
.PHONY : utest/fast

ttree.o: ttree.c.o
.PHONY : ttree.o

# target to build an object file
ttree.c.o:
	$(MAKE) -f CMakeFiles/ttree.dir/build.make CMakeFiles/ttree.dir/ttree.c.o
.PHONY : ttree.c.o

ttree.i: ttree.c.i
.PHONY : ttree.i

# target to preprocess a source file
ttree.c.i:
	$(MAKE) -f CMakeFiles/ttree.dir/build.make CMakeFiles/ttree.dir/ttree.c.i
.PHONY : ttree.c.i

ttree.s: ttree.c.s
.PHONY : ttree.s

# target to generate assembly for a file
ttree.c.s:
	$(MAKE) -f CMakeFiles/ttree.dir/build.make CMakeFiles/ttree.dir/ttree.c.s
.PHONY : ttree.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... docs"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ttree"
	@echo "... t_balance"
	@echo "... t_cursor_move"
	@echo "... t_init"
	@echo "... t_lookup"
	@echo "... tests"
	@echo "... utest"
	@echo "... ttree.o"
	@echo "... ttree.i"
	@echo "... ttree.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

